# Generated by Django 4.0.2 on 2022-02-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_relationship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'РУБРИКИ'},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='articles.tag', verbose_name='Выбор рубрики'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная рубрика'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='Разное', max_length=32, verbose_name='Название рубрики'),
        ),
    ]
