# Generated by Django 4.0.1 on 2022-01-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_images_alter_phone_lte_exists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='images',
            new_name='image',
        ),
    ]
