# Generated by Django 4.0.1 on 2022-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_rename_images_phone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
